# This workflow builds, tests, and releases the dictionary files.
# It can be triggered manually, on a schedule, or when a new tag is pushed.

name: Build and Update Dictionaries

# Controls when the action will run.
on:
  # Allows manual runs from the Actions tab on GitHub.
  workflow_dispatch:

  # Runs on a schedule (at 00:00 on Jan 1st and Jul 1st).
  schedule:
    - cron: '0 0 1 1,7 *'

  # Runs when a tag matching the v*.*.* pattern is pushed.
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Define permissions for the job.
    # 'contents: write' is required for committing files and creating releases.
    permissions:
      contents: write

    steps:
      # 1. Check out your repository code so the workflow can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up the specific version of Python required by the script.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install Python dependencies defined in the script.
      - name: Install dependencies
        run: |
          set -x # Print each command before executing it
          python -m pip install --upgrade pip
          # Add missing 'jaconv' dependency
          pip install kanjiconv sudachipy sudachidict_core jaconv

      # 4. Prepare all source dictionary files needed by the Python script.
      - name: Prepare Dictionary Files
        run: |
          set -x # Print each command for debugging
          echo "--- Setting up directories ---"
          mkdir mozc dic
          
          echo "--- Cloning merge-ut-dictionaries ---"
          git clone https://github.com/utuhiro78/merge-ut-dictionaries.git
          
          echo "--- Modifying build scripts ---"
          MERGE_SCRIPT_PATH="merge-ut-dictionaries/src/merge/make.sh"
          JAWIKI_SCRIPT_PATH="merge-ut-dictionaries/src/jawiki/make.sh"

          # --- Modify merge/make.sh ---
          # neologdを有効化
          sed -i 's/#neologd="true"/neologd="true"/' "$MERGE_SCRIPT_PATH"
          # sudachidictを無効化
          sed -i 's/sudachidict="true"/#sudachidict="true"/' "$MERGE_SCRIPT_PATH"
          # ソースからビルドする設定を有効化
          sed -i 's/#generate_latest="true"/generate_latest="true"/' "$MERGE_SCRIPT_PATH"
          # サブスクリプトの呼び出しを 'sh' から 'bash' に変更
          sed -i 's/sh make.sh/bash make.sh/g' "$MERGE_SCRIPT_PATH"
          
          # --- Modify jawiki/make.sh to download the correct index file ---
          # 巨大なXMLファイルではなく、正しい索引ファイルをダウンロードするようにURLを修正
          sed -i "s|'https://dumps.wikimedia.org/jawiki/latest/jawiki-latest-pages-articles-multistream.xml.bz2'|'https://dumps.wikimedia.org/jawiki/latest/jawiki-latest-pages-articles-multistream-index.txt.bz2'|" "$JAWIKI_SCRIPT_PATH"

          echo "--- Verifying modified merge/make.sh ---"
          cat "$MERGE_SCRIPT_PATH"
          echo "--- Verifying modified jawiki/make.sh ---"
          cat "$JAWIKI_SCRIPT_PATH"
          
          echo "--- Running build script with enhanced error checking ---"
          # Add 'set -e' to the subshell to ensure it exits immediately on any error.
          (cd merge-ut-dictionaries/src/merge && set -e && bash make.sh)

          echo "--- Build script finished successfully. ---"

          echo "--- [DEBUG] Listing contents of the work directory ---"
          ls -lR merge-ut-dictionaries/work || echo "work directory not found or is empty."

          echo "--- Moving generated dic files ---"
          # ビルド対象の辞書ファイルのみを移動する
          mv merge-ut-dictionaries/work/jawiki-*.txt ./dic/wiki.txt
          mv merge-ut-dictionaries/work/NEologd-*.txt ./dic/neologd.txt
          # personal-names は jp-names-*.txt として出力される
          mv merge-ut-dictionaries/work/jp-names-*.txt ./dic/names.txt
          mv merge-ut-dictionaries/work/jawiki-place-*.txt ./dic/place.txt

          echo "--- Verifying contents of ./dic directory ---"
          ls -lR dic
          
          echo "--- Downloading Mozc dictionary files ---"
          MOZC_BASE_URL="https://raw.githubusercontent.com/google/mozc/master/src/data/dictionary_oss"
          for i in $(seq -f "%02g" 0 9); do
            wget -P ./mozc/ "${MOZC_BASE_URL}/dictionary${i}.txt"
          done
          wget -P ./mozc/ "${MOZC_BASE_URL}/suffix.txt"

          echo "--- Verifying contents of ./mozc directory ---"
          ls -lR mozc
          echo "--- Source dic files prepared. ---"

      # 5. Run the main Python script to process and filter all dictionaries.
      - name: Run dictionary processing script
        run: |
          set -x # Print each command for debugging
          echo "--- Listing files before running Python script ---"
          ls -lR
          echo "--- Running Python script ---"
          python ./process_dictionaries.py
          echo "--- Python script finished ---"
          echo "--- Listing generated .txt files ---"
          ls -l *.txt

      # 6. Commit and push updated files on scheduled runs.
      - name: Commit files
        if: github.event_name == 'schedule'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(bot): Automatically update dictionary files"
          file_pattern: "*.txt" # Commits all changed .txt files in the root.
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions[bot]@users.noreply.github.com>"

      # 7. Package generated dictionary files into a zip archive for the release.
      - name: Package release artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -x # Print each command for debugging
          echo "--- Listing files to be zipped ---"
          ls -l *.txt
          zip dictionary-artifacts.zip *.txt
          echo "--- Verifying created zip file ---"
          ls -l dictionary-artifacts.zip

      # 8. Create a new GitHub Release and upload the zip archive as an asset.
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dictionary-artifacts.zip
          name: Dictionary Release ${{ github.ref_name }}
          body: |
            Automated release of updated dictionary files.
            The attached zip file contains all generated dictionaries.
