name: Build Mozc UT Dictionaries

permissions:
  contents: write   # リリース作成に必要

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: ${{ github.workspace }}/artifacts
    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git bzip2 python3 python3-pip

      - name: Clone merge-ut-dictionaries
        run: git clone --depth 1 https://github.com/utuhiro78/merge-ut-dictionaries.git

      - name: Build individual dictionaries
        working-directory: merge-ut-dictionaries/src/merge
        run: |
          set -euxo pipefail
          mkdir -p "${OUTPUT_DIR}"

          for dict in jawiki neologd personal_names place_names; do
            # すべて false 化
            sed -i -E 's/^((alt_cannadic|edict2|jawiki|neologd|personal_names|place_names|skk_jisyo|sudachidict))="true"/#\1="true"/' make.sh
            # ターゲットのみ true 化
            sed -i -E "s/^#(${dict})=\"true\"/${dict}=\"true\"/" make.sh

            sh make.sh
            mv mozcdic-ut.txt "${OUTPUT_DIR}/mozcdic-ut-${dict}.txt"
          done

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: mozcdic-ut-txts
          path: ${{ env.OUTPUT_DIR }}/*.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # ★ artefact をワークスペース直下に展開
      - uses: actions/download-artifact@v4
        with:
          name: mozcdic-ut-txts
          path: .              # ← ここを “.” に

      # ★ ワイルドカードでまとめて渡しても可
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            mozcdic-ut-jawiki.txt
            mozcdic-ut-neologd.txt
            mozcdic-ut-personal_names.txt
            mozcdic-ut-place_names.txt
