name: Build Mozc UT Dictionaries

# === ① リリース作成用に contents:write を付与 =========================
permissions:
  contents: write          # softprops/action-gh-release が 403 を出さないように

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'               # v1.0.0 などのタグ push でリリース

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: ${{ github.workspace }}/artifacts
    steps:
      # 0) チェックアウト（成果物を添付できるように）
      - uses: actions/checkout@v4

      # 1) 依存インストール
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git bzip2 python3 python3-pip

      # 2) リポジトリを浅くクローン
      - name: Clone merge-ut-dictionaries
        run: |
          git clone --depth 1 https://github.com/utuhiro78/merge-ut-dictionaries.git

      # 3) 単一ソース辞書を 4 種類ビルド
      - name: Build individual dictionaries
        working-directory: merge-ut-dictionaries/src/merge
        run: |
          set -euxo pipefail
          mkdir -p "${OUTPUT_DIR}"

          # ビルド対象
          for dict in jawiki neologd personal_names place_names; do
            # すべてコメントアウト（true → #true）
            sed -i -E 's/^((alt_cannadic|edict2|jawiki|neologd|personal_names|place_names|skk_jisyo|sudachidict))="true"/#\1="true"/' make.sh
            # 対象のみ有効化（#true → true）
            sed -i -E "s/^#(${dict})=\"true\"/\\1=\"true\"/" make.sh

            # ビルド実行
            sh make.sh

            # 出力をリネームして退避
            mv mozcdic-ut.txt "${OUTPUT_DIR}/mozcdic-ut-${dict}.txt"
          done

      # 4) アーティファクトとしてアップロード
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: mozcdic-ut-txts
          path: ${{ env.OUTPUT_DIR }}/*.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          name: mozcdic-ut-txts

      # === ② softprops/action-gh-release は何も指定しなければ
      #      GITHUB_TOKEN を自動使用。上の permissions で書き込み許可済み
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mozcdic-ut-jawiki.txt
            mozcdic-ut-neologd.txt
            mozcdic-ut-personal_names.txt
            mozcdic-ut-place_names.txt
