name: Build Mozc UT Dictionaries
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'       # trigger release when a version tag such as v1.0.0 is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: ${{ github.workspace }}/artifacts
    steps:
      # 0) Checkout (your) repository – needed so that artifacts can be attached to it
      - uses: actions/checkout@v4

      # 1) Install basic dependencies
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git bzip2 python3 python3-pip

      # 2) Clone the merge‑ut‑dictionaries project (shallow)
      - name: Clone merge‑ut‑dictionaries
        run: |
          git clone --depth 1 https://github.com/utuhiro78/merge-ut-dictionaries.git

      # 3) Build four “single‑source” dictionaries
      - name: Build individual dictionaries
        working-directory: merge-ut-dictionaries/src/merge
        run: |
          set -euxo pipefail
          mkdir -p "${OUTPUT_DIR}"
          # list of sources to build one‑by‑one
          for dict in jawiki neologd personal_names place_names; do
            # Comment‑out *all* sources
            sed -i -E 's/^(alt_cannadic|edict2|jawiki|neologd|personal_names|place_names|skk_jisyo|sudachidict)="true"/#\1="true"/' make.sh
            # Uncomment the one we want for this loop
            sed -i -E "s/^#(${dict})="true"/\1="true"/" make.sh

            # Run the build
            sh make.sh

            # Rename the output and move it to the central folder
            mv mozcdic-ut.txt "${OUTPUT_DIR}/mozcdic-ut-${dict}.txt"
          done

      # 4) Upload build artefacts so other jobs (or users) can grab them
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: mozcdic-ut-txts
          path: ${{ env.OUTPUT_DIR }}/*.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          name: mozcdic-ut-txts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mozcdic-ut-jawiki.txt
            mozcdic-ut-neologd.txt
            mozcdic-ut-personal_names.txt
            mozcdic-ut-place_names.txt
