# .github/workflows/build-ut.yml
name: Build single-source UT dictionaries

on:
  workflow_dispatch:      # 手動実行
  push:                   # または main への push
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        src: [jawiki, personal_names, place_names, neologd, sudachidict]

    steps:
      - uses: actions/checkout@v4

      # 依存 Python が必要な場合は有効に
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clone merge-ut-dictionaries
        run: |
          git clone --depth 1 https://github.com/utuhiro78/merge-ut-dictionaries.git

      - name: Build ${{ matrix.src }} only
        working-directory: merge-ut-dictionaries/src/merge
        run: |
          # ------ ① すべて false で初期化 ------
          export alt_cannadic="false"
          export edict2="false"
          export jawiki="false"
          export neologd="false"
          export personal_names="false"
          export place_names="false"
          export skk_jisyo="false"
          export sudachidict="false"

          # ------ ② 今回だけ true に ------
          export ${{ matrix.src }}="true"

          # ------ ③ make.sh 実行 ------
          sh make.sh

          # make.sh の最終成果物は mozcdic-ut.txt として
          # カレントに置かれるので、わかりやすい名前へ
          mv mozcdic-ut.txt ../../mozcdic-ut-${{ matrix.src }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mozcdic-ut-${{ matrix.src }}
          path: merge-ut-dictionaries/mozcdic-ut-${{ matrix.src }}.txt
